apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mysql-ecom-instance
  namespace: db-surprising-namespace
spec:
  clusterServiceClassExternalName: mysql-artifact-service
  clusterServicePlanExternalName: default
  parameters:
    Size: 30
    cluster: ecom
    Artifact: com.company.ecom.catalog
    BI: false
    Backup: true
    RAM: 32
    CPU: 8
    Segment: editor
    NumOfReplicas: 3