apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mysql-editor-instance
  namespace: test-ns
spec:
  clusterServiceClassExternalName: mysql-artifact-service
  clusterServicePlanExternalName: default
  parameters:
    Size: 30
    cluster: editor
    Artifact: com.company.editor.html-editor
    BI: false
    Backup: true
    RAM: 32
    CPU: 8
    Segment: editor
    NumOfReplicas: 3