apiVersion: v1
kind: Template
metadata:
  name: mysql-osb
objects:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: mysql-osb-client

- kind: Secret
  apiVersion: v1
  metadata:
    name: mysql-osb
    annotations:
      kubernetes.io/service-account.name: mysql-osb-client
  type: kubernetes.io/service-account-token

- apiVersion: servicecatalog.k8s.io/v1beta1
  kind: ClusterServiceBroker
  metadata:
    name: mysql-osb
  spec:
    url: https://mysql-osb.mysql-osb.svc.cluster.local
    caBundle: ${BROKER_CA_CERT}
    authInfo:
      bearer:
        secretRef:
          namespace: ${NAMESPACE}
          name: mysql-osb

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: mysql-osb

- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: mysql-osb
  rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]

- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: access-mysql-osb
  rules:
  - nonResourceURLs: ["/v2", "/v2/*"]
    verbs: ["GET", "POST", "PUT", "PATCH", "DELETE"]

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: mysql-osb
  subjects:
    - kind: ServiceAccount
      name: mysql-osb
      namespace: ${NAMESPACE}
  roleRef:
    kind: ClusterRole
    name: mysql-osb

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: mysql-osb-client
  subjects:
    - kind: ServiceAccount
      name: mysql-osb-client
      namespace: ${NAMESPACE}
  roleRef:
    kind: ClusterRole
    name: access-mysql-osb

- kind: Service
  apiVersion: v1
  metadata:
    name: mysql-osb
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: 'mysql-osb-ssl'
    labels:
      app: mysql-osb
  spec:
    selector:
      app: mysql-osb
    ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: mysql-osb
    labels:
      app: mysql-osb
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mysql-osb
    template:
      metadata:
        labels:
          app: mysql-osb
      spec:
        serviceAccount: mysql-osb
        containers:
        - name: service-mysql-osb
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          command:
          - /opt/servicebroker/servicebroker
          args:
          - --port
          - "8443"
          - -v
          - "4"
          - --logtostderr
          - --tls-cert-file
          - "/var/run/mysql-osb/starterpack.crt"
          - --tls-private-key-file
          - "/var/run/mysql-osb/starterpack.key"
          - --authenticate-k8s-token
          ports:
          - containerPort: 8443
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8443
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          volumeMounts:
          - mountPath: /var/run/mysql-osb
            name: mysql-osb-ssl
            readOnly: true
        volumes:
        - name: mysql-osb-ssl
          secret:
            defaultMode: 420
            secretName: mysql-osb-ssl
            items:
            - key: tls.crt
              path: starterpack.crt
            - key: tls.key
              path: starterpack.key

parameters:
- description: Name of the image to use
  displayName: Image name
  name: IMAGE
  required: true
  value: quay.io/mysql-osb/servicebroker:latest

- description: base64 encoded SSL CA Certificate
  displayName: base64 encoded SSL CA Certificate
  name: BROKER_CA_CERT
  required: true
  value: 

- description: Namespace that the starter pack is deployed to
  displayName: Namespace
  name: NAMESPACE
  value: mysql-osb
